### ISSUE TITLE
Use MAC address instead of random number to identify device

### ISSUE THREAD

**Issue by renatobo** [0x8008135/RaceChronoDYI-TBeam#1]
In place of

`String device_name = "RC_DYI_" + String(random(0,65535));`

one could use ESP.getEfuseMac to create an ID unique to each device

`chip = (uint16_t)((uint64_t)ESP.getEfuseMac() >> 32);`

so that it's not random nor it needs to be changed by everyone compiling the code.

**Comment by 4z0x** [comment]
I patched the code as suggested in your issue

https://github.com/0x8008135/RaceChronoDYI-TBeam/commit/1aef53209e63552935d0412ca53eec8af159fe6e

Thanks
