### ISSUE TITLE
iOS - No Satelite Fix 

### ISSUE THREAD

**Issue by johnvants** [0x8008135/RaceChronoDYI-TBeam#5]
Hello, I cannot seem to get this project to fix to satelite using iOS. I have stable BLE connection. Any suggestions or advice? 

Thanks

**Comment by 4z0x** [comment]
Hello,

First thing would be to check the GPS reception using the official `ucenter` program, this can be done by flashing the `passthrough.ino` sketch on your device. You should be able to configure the device and so on.

Some things may go wrong if you are not outside or not using a good antenna. I know that the device works with antennas such as 712-ANT-GPS-SH2-SMA from Mouser OR FXUB63 from TAOGLAS

Let me know if you face any other issues

**Comment by johnvants** [comment]
Thanks for your help. I ran the passthrough which was a good idea. Get a solid lock to 10+ satelites, 115200 baud at 10hz. Still no luck with getting fix to satelite in Racechrono. I'm a bit stumped to be honest. Not sure what else to check but perhaps it's a UUID issue. If you have any other suggestions? Otherwise appreciate your help so far. 

Cheers

**Comment by 4z0x** [comment]
Unfortunately, I do not own any GPS module nor Iphone application  to test my code again ;(

However, I know it works with Iphone since a person I know is using it.... I asked for feedback/screenshots.

I suggest to test your setup with the Android version (if you can), there is a free version which can help you validate your setup.

I'll keep you updated as soon as possible.

**Comment by 4z0x** [comment]
@johnvants can you make a photo of your setup please ? as well describe which esp32 board and ublox module you have ?

Here is my setup, I just changed a few things in the code (RX/TX Pins):

![image](https://github.com/0x8008135/RaceChronoDYI-TBeam/assets/5058971/b4361028-782a-4751-8c92-963d1fc87255)

![IMG_7472](https://github.com/0x8008135/RaceChronoDYI-TBeam/assets/5058971/eda1e8d6-5821-46a1-a4ea-74a131a824ea)
